### ISSUE TITLE
点击率特征

### ISSUE THREAD

**Issue by LuciferTian** [ShusenTang/BDC2019#1]
您好，我用线下两万数据来做，构造点击率特征，重要度排序排在很后边，而且会严重造成数据泄漏。请问这是因为我是在线下做的缘故吗？线上是不是跟线下差别很大？

**Comment by ShusenTang** [comment]
构造点击率特征泄露原因应该是样例2w的数据量太小了

**Comment by ShusenTang** [comment]
> 您好，我用线下两万数据来做，构造点击率特征，重要度排序排在很后边，而且会严重造成数据泄漏。请问这是因为我是在线下做的缘故吗？线上是不是跟线下差别很大？

构造点击率特征泄露原因应该是样例2w的数据量太小了
